spring:
  datasource:
    url: jdbc:mysql://localhost:3307/expenses_handler?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

jwt:
  secret: "b4c8fce6d9f4a1b7d92a6d0c3f8f45a87bcb4e6fca9d7a8f5e2b9c7d4a8e6c3fb2a1d4f7c9e6a2f1d7c4b9e8f3a6c2d9"




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true