server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # Don't register itself as a client
    register-with-eureka: false
    # Don't fetch registry information
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    # Disable self-preservation mode in development
    enable-self-preservation: false
    # How often to clean up expired instances
    eviction-interval-timer-in-ms: 10000

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG